package org.omg.Messaging;


/**
* org/omg/Messaging/SYNC_WITH_TRANSPORT.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /scratch/jenkins/workspace/8-2-build-linux-amd64/jdk8u261/295/corba/src/share/classes/org/omg/PortableInterceptor/Messaging.idl
* Wednesday, June 17, 2020 11:43:21 PM PDT
*/

public interface SYNC_WITH_TRANSPORT
{

  /**
     * Constant, defined in the Messaging spec, to define how far the 
     * request shall progress before control is returned to the client.
     */
  public static final short value = (short)(1);
}
