package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/DISCARDING.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /scratch/jenkins/workspace/8-2-build-linux-amd64/jdk8u261/295/corba/src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Wednesday, June 17, 2020 11:43:21 PM PDT
*/

public interface DISCARDING
{

  /** Object adapter state that causes all requests to be discarded.
     */
  public static final short value = (short)(2);
}
